### ISSUE TITLE
Bug: S2 Clicking browser Back button moves onboarding process forward

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#115]
Site: live, dev

To reproduce:
1. sign up as a professional
2. confirm your email address
3. start the onboarding process (creating job title, etc)
4. once you are two or three steps into the process, click the browser back button
5. you will advance in the onboarding process
6. continue clicking the back button until you see the confirmation screen saying the onboarding process is complete.
7. return to the _Job Titles_ listing page in the admin interface, see that your job title has steps left to activate.

To fix:
The back button should either return to the previous step in onboarding, or we should ask the user if they want to pause the onboarding process.

**Comment by situatedbit** [comment]
More details on this:
- The _Back_ button only navigates forward in the onboarding process when it is clicked on the _Tell Us About Yourself_ page.
- However, generally, if the _Back_ button is clicked during the onboarding process, followed by the user clicking _Save and Continue_ on most of the forms, causes the onboarding process to move one step forward beyond the latest form the user has seen. The content on that form is skipped. This creates holes in the onboarding and profile data.

**Comment by situatedbit** [comment]
Discovered several bugs during this and am addressing them together.

1. When the user clicks _back_ during onboarding process, then presses the _save and continue_ button, the app skips the next screen and saves the new position in the database. Example: given onboarding screens 1, 2, 3, and 4. The user is on screen 2, but has not completed the form on screen 2. They press the _back_ button. They are now on screen 1. They _save and continue_ from screen 1, and the app will navigate them directly to screen 3 and save that status in the database. But, they never completed screen 2.

2. Clicking _back_ on the _Tell us about yourself_ screen navigates the user forward in the onboarding process. The user can continue to press the back button and is carried through the onboarding process to the end. (This is the original bug for this issue).

## Other Bugs Found While Addressing 1 and 2

1. If you navigate _back_ from the servicesOverview page, then return to the page to complete it, _sometimes_ you are not allowed to submit the form. The error message is ``POST is not allowed`. The problem here is that the jobTitleID is discarded at some point, and the servicesOverview page tries to create a new ``servicesAttribute`` object, rather than updating it with a ``PUT``.

2. Sometimes the URL for servicesOverview does not contain the job title ID when coming from schedulePreferences, however, I'm not able to reliably reproduce this.

3. While using the _back_ and _forward_ browser buttons during the onboarding process, I occasionally encounter the credentials forms for job title Dog Walker. In this case, the credentials page should be skipped.

4. If the user completes the addJobTitle form, navigates forward, then navigates back to addJobTitle, they become stuck in the navigation. It only allows them to _add_ a new job title. If they've already add the job title then there is nothing to do. (It is possible to click on the "Finish Profile" button in the main menu, but this is generally difficult to discovery for the typical case.)

5. On _dev_,  start onboarding. Then log out. Return to the site and log in. The user is supposed to resume onboarding, but instead sees the dashboard without a completed profile. Also, there is no "Finish Profile" link in the menu.


More details on this:
- The _Back_ button only navigates forward in the onboarding process when it is clicked on the _Tell Us About Yourself_ page.
- However, generally, if the _Back_ button is clicked during the onboarding process, followed by the user clicking _Save and Continue_ on most of the forms, causes the onboarding process to move one step forward beyond the latest form the user has seen. The content on that form is skipped. This creates holes in the onboarding and profile data.

**Comment by IagoSRL** [comment]
This happened to me when testing #138 at Safari 9.0.3 on Mac OS X El Capitan 10.11.3, at last, paymentAccount step, going back and click save&continue goes to post-onboarding screen, and onboarding being set as completed (skipping last step).

I'm thinking if we must remove the multiple-activity approach here, move most things to components (or reusable viewModels and templates) and have just an 'onboarding' activity. Similar to what I'm thinking to do to the 'appointment' activity, using same approach as 'booking'. Maybe even better for automated tests?

**Comment by joshdanielson** [comment]
@IagoSRL I like that idea knowing what's in onboarding may change over time (adding/removing). I'll leave it up to you and @situatedbit.

**Comment by IagoSRL** [comment]
@situatedbit Let chat about this next week (or left any comment before if want), to check how much progress you have on this and how do you see the possibility to refactor the onboarding and all involved activities (I can take that task); we need to decide if is worth specifically fix this back-button bug, or go to refactor getting that and maybe others fixed (on this latest case, will get moved to other release).

**Comment by situatedbit** [comment]
@IagoSRL Josh and I spoke about our options to make onboarding better in the near-term. We decided that we'd like to disable the back button during onboarding. To mitigate any sense of wasted effort on the part of providers, we'll change the language during onboarding to encourage them to create 1 job title and 1 service, then add more later on.

There are two consequences for the code I have been working on:
1. I would like to include some of the refactoring of onboarding I have already committed. I removed some unused code and added a little more data hiding to the Onboarding view model.
2. We need to fix ``shell.go(, , replaceState = true)``. I would like to take this on, but @IagoSRL, would you be willing to share any insight you have about ``hashbangHistory.js``? Are there any other bugs that you know about or code that is not being used?

I think maybe in the future it makese sense to make onboarding into an ``Activity``, but at the moment I don't think the substantial code changes are worth it in the near-term.

@joshdanielson tell me what you think of the language on these mockups: https://loconomics.mybalsamiq.com/projects/onboarding-no-back/grid

**Comment by IagoSRL** [comment]
@situatedbit Let me review some things.. at the top of the file /shell/hashbangHistory.js I wrote a TO-DO time ago explaining the know-bug, and an idea of solution. I tried that before comment it, I had the change stashed in my local git but didn't worked and had other priorities by then, let me check it and do some more trial and upload in a experimental branch; as commented yesterday, we can try another idea, to rely on browser replaceState to change the hashbang value.

FYI: Time ago, the *state* of HTML5 HistoryAPI was discouraging, with initial webkit implementations being so buggy that were not reliable (as caniuse.com still says, affected Chrome, Safari, iOS, Android); I had personal headaches with that on website projects time ago, leading me to avoid it hoping to be able to rely on that at some *near future* -maybe just today?- were it *just worked*; maybe even creating a blacklist of know bad implementations where fallback to that, Twitter original's, hashbang approach; because a simplistic feature test to check that 'pushState' exists on browser is not enough. There is even an open Chrome bug today still (history state not preserved if tab goes to another origin and then go back); I suppose others stop relying on saved state or don't care about that edge case.

I used libraries as popular history.js, does really good things but trying to fix so many browser quirks that is complex and still not perfect; and I had problems to use at a Phonegap environment (file:// protocol), so I created hashbangHistory.js, more simple and focused, easier to test, with some tricks learn from there (like the use of _suid param to track state differences). Another goal of my module was to try to implement the same API than standard history, so are interchangeable (for example, Shell references to browser *history* instance by default). The downside is the bug with replaceState, I didn't find more though but let me know if any.

I didn't updated my knowledge on this topic from a while, so maybe new techniques or approaches are preferred today.

**Comment by joshdanielson** [comment]
@situatedbit here are some minor revisions. We'll run them by @kyraharrington tomorrow as well.
## /addJobTitles
"Create your first listing"
paragraph text looks great
"Add a job title" (and then let's limit it to one)

If we feel confident that clicking on the job title when searching is enough, we could skip to the next screen and save them a "save and continue". Up to you.

## /servicesOverview
- all good!

## /addOfferings
- all good!

**Comment by situatedbit** [comment]
@IagoSRL Thanks for the summary. I'll take a look at hashbangHistory so I understand exactly how it works. Even if the state of the history api is now good, I am hesitant to replace hashbangHistory — are there unexpected side-effects or are there parts of the app that assume history + navigation using hashbang?

**Comment by IagoSRL** [comment]
@situatedbit you are right about dependency doubts on hashbang: even if Shell and it's calls to history were done to work both with hashbanghistory or just browser history, this latest was not tested well (since we were using hashbang all the time) but most important, lot of places the app has links formatted with the hashbang prefix.

Remembering well, the parseUrl at /shell was implemented thinking in the possibility of receive hashbang links in a context where native history is in use, cleaning-up the input URL when analyzing, that's something I did expecting the transition between both kind of links, but again, not fully tested. So we will keep the hashbangHistory for a while, is not so priority to switch it, except if some unavoidable bug appears (that I hope not!).

[Sorry for the long texts]

**Comment by situatedbit** [comment]
@IagoSRL thank you  - this is helpful. I also think I understand now how hashbangHistory works, and I see how replaceState is not working as expected. The fix, however... I have to think about that :)

**Comment by IagoSRL** [comment]
@situatedbit I uploaded to master a documentation update at hashbangHistory comments (that I had stashed previously), and ideas for the fix (too at the initial comment, TODO-2).
Added a new branch hashbang-replace-state-trial that have my old, stashed, trial to make *replaceState* works, by using the 'history.back' trick (first idea in the comment); didn't worked, from what I remember, and still has limitations, but just if you want to try or check; I wrote another *crazy* idea as alternative B; and C is just to use native replaceState if available.

**Comment by IagoSRL** [comment]
Was reading the code of History.js project (https://github.com/browserstate/history.js/blob/master/scripts/uncompressed/history.html4.js, https://github.com/browserstate/history.js/blob/master/scripts/uncompressed/history.js) just to see if it has a solution for that...but no, it just has the same bug (replaceState on "html4" -hashbang- is just an alias to pushState).

**Comment by situatedbit** [comment]
Thanks for posting TODO-2. 

TODO-1: I did a little testing around how we might use go(-1), and one of the major problems I see is that even between Firefox and Chrome, the behavior is quite different. Chrome updates window.location asynchronously after go(-1). This would break Shell.replace, as far as I understand it, or require us to do something really complicated. 

TODO-2: this is funny because I was thinking about my own version of TODO-2, and came across the same limitations. Also, when we land on a Bad/Replaced URL, we don't know if the user was navigating backwards or forwards (or clicked on that URL in the history list), so we can know whether to go(-1) again, or go(1). 

TODO-3 (C): I think we should consider this. What browsers do we support?

D: We modify onboarding so users are always redirected to the furthest activity that they have not completed. One downside with this is that it will fill up the browser history with useless back URLs.

I was actually thinking through my own version of TODO-2, and I think one of

**Comment by IagoSRL** [comment]
Answering per point:

- TODO-1: maybe a solution is to wrap code in an immediate setTimeout(..., 1), so will be quick but let happens the async url change?

- TODO-2: good point; we need a vector here..how? I don't want to add an _suid for everyone in order to have an index to compare; maybe we can keep our list of history entries and look by index; if we get that, for user picking manually the *bad* entry, will need to skip it, going back if older than current one and forward if newer.
**Give a try to your ideas here**

- TODO-3: We are supporting Android 4, 4.1 that has no support (or has but is too buggy? maybe had enough replaceState, giving that we will keep using our state management). Maybe we can drop them? I think other supported engines must be *fine* right now (iOS 7+...maybe we can update this to 9+?,  modern Firefox and Chrome; Microsoft Edge but not IE).

- D: I think we only push one history entry only, since we jump directly to the last onboarding step (after a log-in)....right now, except you are thinking in fill all steps in history to make the go-back to effectively go to previous onboarding step (don't think is needed, if they come from log-in and press back, they must return to log-in).

More tomorrow, don't think clearly right now (tired, late here).

**Comment by situatedbit** [comment]
I'm going to look at these options today. As of right now, I'm most optimistic about them in this order: TODO-3, TODO-1, D, TODO-2.

**Comment by situatedbit** [comment]
As if we don't have enough ideas already... here's another idea:

We use ``replaceState()`` on the browsers that support it, and then fall back to the current behavior for browsers that do not. We can use [modernizr](https://github.com/Modernizr/Modernizr) to do this detection within hashbangHistory. (see https://github.com/Modernizr/Modernizr/blob/master/feature-detects/history.js). 

Since [Android 4.3+ has full support for the History API](http://caniuse.com/#search=history), and [~10% of Android users are on _older_ versions](https://developer.android.com/about/dashboards/index.html), we would get the behavior we want for a vast majority of users across platforms.

For those using older browsers, the behavior will be no worse than it is today.

In the future, as we use ``replaceState``, we'll have to build our activities and task paths so they are robust enough to not break if ``replaceState`` doesn't work, or that they offer replacement features when it does — we'd have to code defensively. For example, eventually we should add a _Start Over_ option within onboarding.

**Comment by situatedbit** [comment]
@IagoSRL I'm testing out using the real ``replaceState`` on supported browsers. I'm checking all of the places where we use ``shell.go(, , replaceState = true)`` and I notice this happens a lot in adjusting the URL in activities. 

Here's an example from ``activities/serviceProfessionalService.js``. I have some questions in the comments: 

```javascript
    this.registerHandler({
        target: this.viewModel.jobTitleID,
        handler: function(jobTitleID) {
            if (jobTitleID) {
                /// Rewrite URL
                // IMPORTANT: When in isSelectionMode, pushState cannot be use
                // because it conflicts with the selection logic (on new-booking progress)
                // TODO: discarded URL rewrite until the bug with replaceState in HashbangHistory is fixed

/* ?: if we fix replaceState for modern browsers, what will happen on 
        Android 4 if we remove this line? ↓*/
                if (this.viewModel.isSelectionMode()) return;
                // If the URL didn't included the jobTitleID, or is different,
                // we put it to avoid reload/resume problems

/* ?: I understand what this does, but I don't understand why it has to happen ↓ */
                var found = /serviceProfessionalService\/(\d+)/i.exec(window.location);
                var urlID = found && found[1] |0;
                if (urlID !== jobTitleID) {
                    var url = '/serviceProfessionalService/' + jobTitleID;
                    if (this.viewModel.isAdditionMode()) url += '/new';
                    this.app.shell.replaceState(null, null, url);
                }
            }
        }.bind(this)
    });
```

**Comment by situatedbit** [comment]
@IagoSRL I have a working solution in this branch that uses modernizr and the native replacestate. I've looked at all of the code points where we use replaceState, and generally I think this fix won't break anything. I wasn't able to test it against browsers that don't support replaceState natively. Will do that tomorrow. 

I'm still curious about the common pattern used my comment above where URLs are fixed. Also, the ``appointment`` activity was using replaceState in some code paths that I did not know how to test.

Do we have access to an Android 4.0 device? If Josh doesn't think we need to support it, perhaps we can just drop it. I tried testing this code on my old Android 4.2 (!), but there were CSS problems preventing me from using the site.

https://github.com/loconomics/loconomics/compare/is-history-replacestate

**Comment by IagoSRL** [comment]
@situatedbit I think is a good decision.

Good to see Modernizr moved from the one-liner 'pushState in window.history' to some browser sniffing for bad implementations. It lacks still bad old Safari (not a problem now since looks that versions are not used anymore) and surprise they included only Android 4.0.x, not 4.1.

Older Android device version I have now is a 4.4.4 (newest 7.1.1). For older we *may* use the simulator. I didn't have time to test back to 4.0-4.3, still surprise to see something we used is incompatible at 4.2. As @joshdanielson commented at #237, we may drop support for ones below 1.0%, and they seems to fall at that per caniuse/statcounter stats; our current resources are very constrained, we may recover support for them if we found actual needs from our users.

Looking at Google Play Developer dashboard, our current short list of installations don't throw enough information, but too provide a global stat for Productivity apps category where we found:
Android 6.0  45,09%
Android 4.4  18,52%
Android 5.1  14,76%
Android 5.0  12,13%
Android 4.2  3,73%
Android 4.1  1,85%
Android 4.3  1,53%
Android 7.0  1,25%
Android 7.1  0,67%
Android 4.0.3 - 4.0.4  0,35%

At [Google app store stats](https://developer.android.com/about/dashboards/index.html), things are a bit different, but not too much.
Obviously only accounting Android devices they are bigger than global Statcounter. I think still we can move on dropping previous to 4.3 (or 4.4?) in order to move on keeping and eye on users requests.
**What do you think?**

------------

Making another review, I found a possible headache: the exception Modernizer does for file protocol, as of   
https://github.com/Modernizr/Modernizr/pull/1592/files
That makes me think that the updated test as of today https://github.com/Modernizr/Modernizr/blob/master/feature-detects/history.js maybe is doing the *file* check wrongly.
We need to check

**Comment by IagoSRL** [comment]
(I updated my latest comment, I clicked Comment ahead of time)

**Comment by IagoSRL** [comment]
@situatedbit About code:
- the *isSelectionMode* was done because, by *replaceState* doing a *pushState*, when the activity performs a *back* to return to the activity that asked to select something, it will fail because will not return to the requester activity, just to a previous URL on the current one. A *go(-2)* could fix it on that cases. This makes me think that we may need to add a flag for feature support, like *app.shell.isReplaceStateSupported* (?).
- the URL check: ensuring to not do a *replaceState* if the replaced and replacement URLs are the same (previously this caused a *pushState*). From what I remember (I must put more code comments), is just that.

**Comment by situatedbit** [comment]
I need to be able to build the Android app. Will try to get that running this morning.

**Comment by IagoSRL** [comment]
@situatedbit We are using PhoneGap Build (PGB) service for that. We have an account with the private app where you can upload the zip and get the build. It's easy. Just prepare the file by running:
> grunt prepare-phonegapbuild

At /app/build/ folder you will have a *phonegap-bundle-dev.zip* file (also a *live* but that's only for deploy at app stores). At PGB press "Upload code" button and pick the zip. To compile a debug version for Android no key is needed, so you will have no problem (when needed, uploaded keys need to be unlocked previously). Wait until is ready, shoot the QR code from the phone to download and install the APK.

For building locally there are a few tips at https://github.com/loconomics/loconomics/blob/master/docs/Deploying%20the%20App.md but I don't use it so may fail some set-up of the config.xml (that works perfect for PGB).

@joshdanielson Please add Matt as collaborator at PGB, and give him the URL so can build for Android.

**Comment by IagoSRL** [comment]
Minor thing: when working on #242 I found that I had still an AVD with Android 4.0.3 for testing app previously; maybe the CSS problem found was related to using Flexbox?

**Comment by IagoSRL** [comment]
@situatedbit When you can, give us an status update on this, and specifically on *replaceState* implementation.

If you think this can take longer (all bugs and details found at this), we can see to back-port finished changes into master, mostly to further test on *dev* and maybe a beta app for a possible collateral fix of #138, what do you think?

**Comment by situatedbit** [comment]
I think we should release 1.2.2 without it. Is that what you are asking?

Here is the dependency chain:
- replaceState in branch ``is-history-replace-state``: I am trying to test on Android (having problems connecting to API, see https://github.com/loconomics/loconomics/issues/244#issuecomment-279546216)
- branch ``is-115`` requires the new replaceState, then small changes to text, and calling replaceState

It is close, but won't be ready this week. I will be back next Monday.

**Comment by situatedbit** [comment]
(but, I still have some time today to make progress on it if I can get the app to work with the API)

**Comment by situatedbit** [comment]
@IagoSRL If we are dropping support for Android 4.3, and we only support modern browsers, then I think we can skip modernizr and _always_ use the native ``replaceState``. I'm testing this now on Android with my onboarding changes in ``is115`` and it is looking good.

What do you think of this strategy?

As for places in the code where we are currently avoiding ``replaceState`` (e.g., changing some of the URLs in activities to include IDs, etc), I think we can leave that code untouched until we're actually working in those places, and then just remove those checks on a case-by-case basis.

**Comment by situatedbit** [comment]
I've been testing this plan in ``is115``. Take a look if you want. 

I'm seeing some unexpected bugs when I move back and forward (especially at addJobTitles), and some of the sub-dialogs are using pushState. For instance, if the user presses the back button later on in onboarding, they may end up on a sub-dialog like adding a location.

I'm going to pick this up when I return.

**Comment by situatedbit** [comment]
Status update:
1. Native replaceState seems to be working well.
2. Sub dialogs for adding service, service address/location, and credential now uses history.go(-1) so it does not stick around in the history list
3. _Current Issue_: services overview form occasionally loses some data if the user navigates back and forward, including the jobTitleID and some form fields. 

I think (3) is the last challenge for this issue.

**Comment by situatedbit** [comment]
I forgot to change some of the copy on the onboarding pages....
