### ISSUE TITLE
Revise App Architecture

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#236]
Based on feedback from users, the architecture of the app needs another iteration. A proposed architecture is shown here:
https://github.com/loconomics/loconomics/projects/3
- [x] navigation links
- [x] menus
- [x] rename simple activities, e.g. ownerInfo
- [x] remove old activities:
 - /scheduling
 - /jobTitles
- ~~merge calendar syncing help article into scheduling preferences article~~

**Comment by situatedbit** [comment]
@joshdanielson 

Some suggestions regarding commented code. Suggesting removing new commented lines, or lines that have been moved between files. 

``app/source/html/activities/account.html``: Remove commented ``<li>`` starting on line 20

``app/source/html/activities/clients.html``: The hard-coded back link to _Client Manager_ appears when the professional is creating a new booking and choosing a client. It overrides the _Cancel_ link on the wide layout, though not the phone layout. 

``app/source/html/activities/userProfile.html``: Remove two large commented blocks in the middle of the file

``app/source/html/parts/AddNewMenuContents.html``: Remove commented lines

``app/source/js/activities/ownerInfo.js``: Bug: ``UserType.serviceProfessional`` rather than ``UserType.isServiceProfessional``

_Education_ activity: To match the link on the Profile page, perhaps change heading here from _Your education_ to _Your training and education_. Also, replace _Add education_ button label with _Add degree or certification_. Change the back link on ``/educationForm`` to _Training and education_

## Calendar
I think we should consider moving _Your availability_ back to _Your Listings_. Conceptually it's odd to flip through calendar days and have the availability options persist at the bottom of the page. On days when I have several items on the calendar (a good thing), those options are buried at the bottom of the page. Ideally, they'd be available under calendar, but not in their present form. Instead of list tile/buttons, they'd be in a context menu, or in some other link to "schedule settings" or something similar.

**Comment by joshdanielson** [comment]
@situatedbit I made all the changes you suggested and fixed the backlink for /clients (cancel now shows correctly when in booking mode) and fixed the "bug" in /ownerInfo.

As far as the weeklySchedule goes, we can't put it in Your Listings as the weekly schedule is for all listings (not specific to Job title). I agree it would be idea to figure out a way to leave it in Calendar but it be more usable. @kyraharrington and I reviewed everything and she said we should worry about this aspect later, which I agree :) I opened up #354 for us to review at a later time.

Can you review my latest commits?

**Comment by situatedbit** [comment]
ok - looks good, though I lack merge permissions. Also I tested the merge between this issue and client-specific offerings and it looks good. (Didn't actually test the code, but the merge was clean)

**Comment by situatedbit** [comment]
![calendar-prefs-links-sketch](https://cloud.githubusercontent.com/assets/6644016/25399045/f3423396-29a2-11e7-8c1a-2c30b655ab6a.png)

**Comment by IagoSRL** [comment]
- What does 'Sync Calendar' button?
- Is not bad vertically aligned at desktop 'Availability Settings'?
- The date header at mobile is not better aligned to the left line --with the time? Or almost at the items text start?

**Comment by situatedbit** [comment]
@IagoSRL I had started combining the sync calendar and schedule preferences forms and realized that it made the whole form way too complicated and messy. We reevaluated the problem, and decided to keep the forms separate and to create two links on the calendar.

- Sync Settings -> calendarSyncing
- Availability Settings -> schedulePreferences

I added the dotted guidelines to suggest that the links and the date heading should line up with them.

New version: 
![calendar-prefs-links-sketch](https://cloud.githubusercontent.com/assets/6644016/25400403/4bffbcb6-29a7-11e7-9fcd-8fddf9cb605c.png)

**Comment by situatedbit** [comment]
I will work on fixing the back link from schedule preferences. I saw your note in the pull request.

**Comment by situatedbit** [comment]
This is what the combined forms looked like -- too messy.

![combined-forms](https://cloud.githubusercontent.com/assets/6644016/25400538/c97508f4-29a7-11e7-8700-9a96f320b694.png)

**Comment by IagoSRL** [comment]
I have coded part of the back button fix, for mobile

**Comment by IagoSRL** [comment]
using the same approach as in others, the 'applyNavbarMustReturn' trick. needs extra for desktop

**Comment by IagoSRL** [comment]
I pushed that code, take a look

**Comment by IagoSRL** [comment]
Agree with the messy form.
Link is more clear named now as 'Sync Settings' (before I have the doubt if was for this or to request to refresh the data). As alternative, to have that link inside schedulingPreferences form, since is not a usual link user will go; too the user will not see the syncing options when at marketplaceProfile activity, where the copied link to settings is.

**Comment by situatedbit** [comment]
I see calendar sync settings as rather distant from schedule preferences. Conceptually, I see schedule preferences between _listings_ and _calendar_. It's closely associated with listings because it is an aspect of the business, whereas calendar syncing is a technical mechanism of the calendars.

My preference for now is to keep the link to calendar syncing with the calendar. I suggest we see how users find it or whether they have trouble.

**Comment by IagoSRL** [comment]
The 'popover' date picker is wrongly positioned now on mobile.

**Comment by IagoSRL** [comment]
I pushed the change to support the 'mustReturn' parameter in the desktop navigation of the schedulingPreferences activity (replacing the back button with 'Your Listing' when coming from there, defaults to Calendar as before).

**Comment by IagoSRL** [comment]
My previous push was rejected, now is there

**Comment by IagoSRL** [comment]
About placing the 'sync' button, I understand what you say @situatedbit, but fore me still makes sense to be as a link at schedulingPreferences ('Availability Settings'), since the user can see it when coming from the calendar, and syncing an external calendar affects availability.
If not makes so much sense coming from Your Listing, well, is still just a link (to be clear: at Availabity Settings, not directly at Your Listing).

**Comment by IagoSRL** [comment]
The popover date picker is perfect now!

**Comment by situatedbit** [comment]
@IagoSRL oops. I didn't see your last two comments before I committed + pushed the Sync Calendar link on the Calendar. After talking with Josh, we think that we should leave it as it is for now, and then revisit this issue by creating a small menu within the calendar for settings. If you feel strongly that the Sync Calendar link should be Availability Settings, then I will move it there.

**Comment by IagoSRL** [comment]
No worry, I was thinking to ask you to do that anyway for this release and open a spin-off issue to research a bit more on that for later, so is OK.
Moved this to QA.

**Comment by joshdanielson** [comment]
@IagoSRL I tested this yesterday and have no additional feedback.

**Comment by IagoSRL** [comment]
OK. I will close this now. If some bug, let open an issue (that we will put at top priority if is a big one)
