### ISSUE TITLE
Professional can see summary of client-specific offerings on client card

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#276]
As a professional, so I can access client-specific offerings, I want to see a summary of client-specific offerings for a client on their client card in the client manager. 

There should be a summary for each job title.

**Comment by situatedbit** [comment]
https://loconomics.mybalsamiq.com/projects/loconomics-pricing/professional%20manages%20client-specific%20pricing

**Comment by situatedbit** [comment]
@IagoSRL I'm working on client-specific pricing again (#4).

My plan is to create a feature branch for #4, and create smaller issues like this one to merge into that feature branch. I would like your feedback before I merge the small issues into the feature branch. When I have finished enough small issues, then we can merge the feature branch for #4 into master, under a full code review.

This issue is not quite done, but can you please check the way I'm using the model API to load the necessary data?

I'm going to start creating presenters for view models. I hope that these will move some of the logic required to connect models together outside of the view models.

**Comment by situatedbit** [comment]
I think I'm done with #276. @IagoSRL could you give it a review before I merge it into the #4 feature branch?

I am stopping short of actually linking to the services activity. This item is just presenting the services on the client editor.

**Comment by situatedbit** [comment]
I just merged is276-client-specific-offering-summary into feature branch is4-client-specific-offerings to move 282 forward, but a review would still be useful on 276

**Comment by IagoSRL** [comment]
Hi @situatedbit In general changes looks fine, just some bugs and comments
- Bug: It seems at [this line](https://github.com/loconomics/loconomics/compare/is276-client-specific-offering-summary#diff-bc20cf55c8e97a6722b77c3cbaa27db2R50) that a reset is needed when no clientID; that is, a 'else { this.viewModel.serviceSummaries([]); }'. If you enter the clientEditor as a client that has services, then enters to create a new client (clientID=0), the list will show the services for the previous one.
- [At this data-binding](https://github.com/loconomics/loconomics/compare/is276-client-specific-offering-summary#diff-4fdfb158958084688ce4e92a7bf90622R79) the option to create a new pricing will appear only when no pricing; it seems that only one special pricing per job title can be added.
- Comment: initial shot for the 'save' and 'delete' buttons before the services looks strange; it's logic, since it applies to the above form, but not sure if is clear for users. Maybe some visual grouping needed (two groups: form with buttons, services); maybe a Box-xs class on each one?
- Comment: when adding a new client, the services 'add pricing' appear; maybe is better to hide on creation and left for later? On that case, the 'auto go back' on saving (*successSave*) may not be wanted, keeping user in the editor so can see appearing the services block just in case want to start adding one, maybe?

**Comment by situatedbit** [comment]
@IagoSRL Thanks for the feedback! 

I'll get to the other items, but to the question of separation and grouping with form elements — @joshdanielson and I talked about how in an ideal case this would start as a "view client" card, with an option to edit the client. I plan to create an issue for that. For _this_ issue, I've made a few changes. I'm curious what the two of you think: 
1. I'm using the _pricings_ rather than _services_ until we change to _offerings_ everywhere.
2. I changed the save and delete button text to refer to the client explicitly
3. I pulled the services listings out of the ```form``` element, which created more separation between the form and the services (also, semantically it's better). 

Here are the narrow and wide views. What do you think?:

![client-editor-narrow](https://cloud.githubusercontent.com/assets/6644016/23723652/d1d0f874-03fe-11e7-83a4-880b55182da6.jpg)
![client-editor-wide](https://cloud.githubusercontent.com/assets/6644016/23723653/d1e8d37c-03fe-11e7-87f2-20f95be4e038.jpg)

**Comment by joshdanielson** [comment]
@situatedbit good call on clarifying the button descriptions. All else looks very straight-forward.

**Comment by situatedbit** [comment]
@IagoSRL 

I've updated the code to reflect your feedback.

1. I clear services before loading the new client data. 
2. I changed the language from _service_ to _pricings_ to suggest to the user that this is the way they can add multiple pricings.
3. I made the changes in the screen shots above ↑
4. I removed services during add client. I kept the logic for automatic go-back because when the professional is creating the client in the process of creating a new booking, within two screens of adding the client they will have the opportunity to add a new pricing specific to the client. I am content to return the user back to the client management screen until we change the client editor to have both view and edit modes.

Please let me know if you have any concerns with my solutions above. Otherwise, I will close this issue.

**Comment by IagoSRL** [comment]
Changes are OK, the visual separation is better now. I agree with close this now and left any additional visual adjustment to review later with the view-edit.
Good job

**Comment by situatedbit** [comment]
Created a new issue to create two modes — view/edit and a client card. #308
