### ISSUE TITLE
Capture & Display User Fee Payments History

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#277]
## Child stories
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **view** information about my past *payments (date, amount, method, description, transaction ID, status)* so I can manage my finances easily.

### Test Cases
1) Make sure there is a way to see past payments
2) Make sure it includes the date
3) Make sure it includes the amount
4) Make sure it includes the payment method, e.g. last 4 credit card digits
5) Make sure it includes the payment plan 
6) Make sure it includes the braintree transaction ID
7) Make sure it includes the payment status (needed?)

### Front-end
- [x] /userFeePayments to display payment history including:
    - Date
    - SubscriptionID
    - Amount
    - PaymentMethod
    - Braintree TransactionID
    - Payment Status 
### JS
- 
### API
-  
### Database
- [x] Create UserFeePayments table with the following fields:
     - UserFeePaymentID
     - UserID
     - PaymentDate
     - PaymentAmount
     - PaymentMethod
     - PaymentPlan
     - PaymentTransactionID (Braintree transactionID, string)
     - PaymentStatus
### Braintree
- [x] Create Scheduled Task for a daily API call to Braintree using [Transaction.Search()](https://developers.braintreepayments.com/reference/request/transaction/search/dotnet) to populate UserFeePayments table with NEW transactions:
`var searchRequest = new TransactionSearchRequest().
    CreatedAt.Between(10.00M, 20.00M 12/17/2015 00:00, 12/17/2015 24:59) AND .Status.Is(TransactionStatus.SETTLED);`
  - match transactions with UserIDs using Transaction's CustomerId?

**Comment by IagoSRL** [comment]
Most of this was released as part of Release 1.4 today, but I still don't pushed the bits for the scheduled task. I have some details to clarify first, in line with #334. I was reviewing the use of [Webhooks](https://developers.braintreepayments.com/reference/general/webhooks/subscription/dotnet) for this, when rather than ask Braintree regularly, they tell us changes or payments done at a subscription, and as part of the subscription comes info for payments; that way one call let us update both database userPaymentPlan and userFeePayments; still may we need a task from ourselves in case a webhook request is lost (we updating, system down, net errors, whatever)?

We use a webhook for the professional paymentAccount status already.

**Comment by IagoSRL** [comment]
This is implemented. The task logic is different from the described initially, it's included as part of the subscription update tasks (#334).

At *dev* for testing

**Comment by IagoSRL** [comment]
Tested, included as part of Release 1.6
