### ISSUE TITLE
Create Scheduled Task to Check/Update Plan

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#329]
Check for:
- trial ending
- upgrades
- downgrades
- past due amounts
- scheduled payment fails
- Others?

**Comment by joshdanielson** [comment]
@IagoSRL can you spec this issue since you know the most about it at this point?

**Comment by situatedbit** [comment]
@IagoSRL Do you have a clear idea for what this item is and how we should do it? Can you please add those thoughts here?

**Comment by IagoSRL** [comment]
Sorry to not spec this and give answer, I have important doubts around this, now I have it more clear, and as commented at #334, most of the work initially expected here will be not needed because of the implementation details there.

Some things still to think about is:
- trial ending: the Braintree webhooks give us notification for this, but not a consistent status to check (when in trial, the status is already Active for the subscription). We can check dates additionally to status to know that (adding a bit more complexity to the #334 impl).
- past due amounts: as previous, managed at #334 and Braintree subscription status updates.
- scheduled payment fails: is managed by #334 too, since that gives a notification of failed charge and changed status for subscription (first past_due -if enabled- then expired/suspended).
- upgrades/downgrades: I don't know exactly if we must do some change here; if user changes plan is actually cancelling a subscription and creating a new one (we will abstract this from user at #278) and that will update OwnerStatus properly, and the paymentPlan choosen that thanks to Abilities #442 will update the UI to reflect the features available.

I'm closing this because I think no work is needed because of was what needed to implement at #334. If we found that forgot some detail that was mean to be done here, we can open a new issue more specific.
