### ISSUE TITLE
Add Braintree Subscription Status Scheduled Tasks

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#334]
Run daily task (Check web codes):
https://developers.braintreepayments.com/reference/response/subscription/dotnet
- check records from our database that are PENDING, PAST_DUE with braintree (Pass in subscriptionIDs to Braintree), get updated data, and update our database with any new statuses, past due fields
- check braintree for subcriptionIDs that are newly CANCELED and EXPIRED UpdatedAt within last X days and update our database
- Make sure the subscriptionIDs reconcile on each end
- If new ACTIVE, run membership checks to enable member
- If new status is CANCELED or EXPIRED, we need to revoke membership and update Owner Status
- If expired and is reactivated, new subscription created with new ID

**Comment by IagoSRL** [comment]
3

**Comment by joshdanielson** [comment]
3

**Comment by situatedbit** [comment]
3

**Comment by IagoSRL** [comment]
@joshdanielson @situatedbit I uploaded code at branch is191 implementing details for this and related issues. Webhooks and schedule task is done for this, but there is additional work for the 'membership checks to enable member' that I need from you to take a look (code starts at https://github.com/loconomics/loconomics/blob/is191-coop-membership/web/App_Code/LcRest/UserProfile.cs#L295)

This implements the 'owner status flow'; we have not a diagram for it but it closely follows the one for [Braintree Suscriptions](https://developers.braintreepayments.com/guides/recurring-billing/overview#subscription-statuses) with the addition that we allow the account to go from cancellation and suspension into active again (for Braintree subscriptions, this are final statuses; from there only a new subscription is allowed, not updates to previous one).
Involved on this are issues #33, #277, #329 (I think this last will not need further work).

There are several methods to review (I tried to make them easy to understand):
- Meets* methods: individual methods to check if every requirement is met (this will be reused at #33 so part of that work is done here --it just needs to set the proper userAlert; think on it as equivalent to a 'TestAlert*' database procedures --we can move SQL code into procs like that ones if needed for consistency).
- CheckOwnerStatus: checks all previous Meet* methods and returns the OwnerStatus expected to set if requirements are met and based on subscription/payment status changes.
- AllowedOwnerStatusChanges index: defines the OwnerStatus flow, restricting the changes from-to statuses.
- Take care that Braintree 'expired' status is being mapped to OwnerStatus 'suspended'.

----

Other notes: I made the scheduled task of this issue, but I limited the execution of that to one day a week to prevent doing more operations and requests to Braintree than needed; usually, the Webhook will just work and that will give us an near instant update.
That same code will manage register the payments for the subscription, since every Subscription object given by Braintree includes a list of latest payments for it. This means that the initial implementation idea for #277 scheduled task changes completely (is managed in the same task that tracks subscription/plan status). Too, notifications of payment charges/error-charging will run the same code for subscription & payments update, and that will trigger the membership check that updates the OwnerStatus.

**Comment by joshdanielson** [comment]
@IagoSRL I reviewed the Meets* methods. The only one I'm questioning with the new "Growth" plan is the MeetsBookingsRequirement as it may be impossible for professionals to meet that one if they're not using our scheduling software (and we don't have the demand for them to get two bookings). Can we remove that one for now (on all plans)? I think that makes most sense. Let me know if you feel otherwise. 

I'm not worried about the bylaws in this case. At some point maybe but in the beginning it's unrealistic.

**Comment by IagoSRL** [comment]
I can if you think is OK with bylaws or any legal thing. I will just comment the code that checks that since is expected we will need to enable this at some point (it makes sense to me to not have the requirement initially -low the barrier- and the exception for plans that cannot apply for it; if a bylaws update is needed to do all correctly let me know).

**Comment by joshdanielson** [comment]
@IagoSRL I think it's okay for now. Low barriers for now!

**Comment by IagoSRL** [comment]
Disabled 'bookings' requirement.
Moved this to QA and #279

**Comment by IagoSRL** [comment]
Tested, included as part of Release 1.6
