### ISSUE TITLE
Configure client-side testing environment

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#336]
From #126 

Let's start with unit testing on the client side.

I will get the following tools working in our client environment:
- https://mochajs.org/
- http://chaijs.com/
- http://sinonjs.org/

Mocha runs the tests. Chai is a set of tools for making assertions in the tests. Sinon allows us to create mocks and stubs in our tests so we can focus our tests and remove dependencies. They're recommended [in this post from 2016](https://medium.com/javascript-and-opinions/state-of-the-art-javascript-in-2016-ab67fc68eb0b#.nogwbau6j). 

This item requires the following: 
- [x] Add MochaJS
- [x] Add ChaiJS
- [ ] Add SinonJS
- [x] Create test task in grunt
- [x] Create a simple test that passes
- [x] Create documentation for how to test with links to resources in our app dev guide

**Comment by situatedbit** [comment]
@joshdanielson I would like to move this one into top priorities. Not because it's going to get us customers faster, but eventually it will help us write code faster and reduce bugs.

**Comment by joshdanielson** [comment]
Done!

**Comment by situatedbit** [comment]
@IagoSRL I was hoping to install [Sinon](https://github.com/sinonjs/sinon) as a part of this task.

When building with browserify, I'm getting a bizzare invalid mapping error. If I set the grunt browserify options to ``debug: false`` the build process works. 

I found [another example of this kind of issue](https://github.com/AgentME/react-hot-transform/issues/2) which was resolved by updating dependencies. I understand that this may not be the same problem, but I did notice that many of our modules are about 3 years old. Several of them are installed with a fixed version (e.g., ``"browserify": "3.46.1",``, currently on version ~15).

I'd like to update several of these modules. Is there a reason that many of them are on fixed versions? I'm also worried that because several of these are quite old, I will have to do a lot of testing to verify that version upgrades don't break our code.

What do you think?

**Comment by IagoSRL** [comment]
@situatedbit I know browserify is out-dated. I even have still an opened tab with their changelog :-O
Tried to upgrade in past, if I remember well problems were about the set-up is different with problems with Grunt set-up (or something like that), its Grunt task did not includes the *shim* plugin and have to figure out how adapt that, some other things. I moved to more productive tasks before lost too much time.

**Things may have changed since that**, maybe easier or just change how we use it for a more modern approach. I even started to evaluate to move to Webapp. If not, we need to upgrated it (even, that old version still uses the original/deprecated source map syntax).

**Comment by IagoSRL** [comment]
And similar with other dependencies (someone because of inter-dependencies) or even approaches; as you can see on your linked article, things changed too fast and too much options in this years for web development; at a crazy level. To change set-up or libs, learn new things, just to do nearly the same but in a different way, is not productive; good things happened in all of that, moving forward, and we will get them (I want to!), but with low resources in a project that is still rushing to *"release"*, keep all that stuff up-to-date with code and set-up changes every couple of weeks pausing feature implementations, sound like a no priority for me. And the problem, once to lost one version, you quickly lost lot more, and become more difficult to update.

A test suite will help a lot with this, because will make us more confident to update dependencies without fear to hidden bugs appearing around.

As an example, Browserify moved from version 3.19 to 8.0 in the same year (2014) and from version 8 to 12 at 2015. 9 major versions with *(maybe)* breaking changes in 2 years. Too fast for me. They have released 395 version up to now.
Maybe to adapt to them is not so difficult, a couple of set-up lines, or not; it's the time to try it :-)

**Comment by situatedbit** [comment]
I agree — all of this changes way too fast.

Here's my suggestion: I will set a time-limit for working on this. If I can update browserify and get it working within an hour, then I'll move forward with it. If I can't finish within that time, then I'll either remove Sinon or set the debug option to false so that it will build, and then create a new issue for updating browserify.

**Comment by IagoSRL** [comment]
OK. Please do it in a new branch from master, so if is correctly updated we can merge back quickly and apply to other active feature branches.

**Comment by situatedbit** [comment]
I tried upgrading Browserify. I made good progress, but it's taking too long. I created #360 and pushed my changes to ``is360-update-browserify``. It's a branch off of master.

I'm going to uninstall Sinon and create an issue to add it.

**Comment by IagoSRL** [comment]
PR merged, and with Sinon set-up 'waiting' at #361 we can close this.

**Comment by IagoSRL** [comment]
thanks @situatedbit
