### ISSUE TITLE
Update Browserify

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#360]
Our current version of Browserify is a few years old. _I think_ it is blocking us from using [Sinon](http://sinonjs.org/) for our client-side testing framework. 

The task is to upgrade browserify to the latest build. This will also require upgrading grunt-browserify, and adding browserify-shim.

**Comment by situatedbit** [comment]
Started working on this. 

Upgraded browserify, grunt-browserify. Had to add browserify-shim.

Current problem: libs.js does not compile the same way as in master. Issues with shimmed libraries. Compare libs.js to the one built in master and figure out why they aren't the same.

**Comment by situatedbit** [comment]
Helpful documentation: 

- https://github.com/defunctzombie/package-browser-field-spec
- https://www.npmjs.com/package/browserify-shim
- https://github.com/jmreidy/grunt-browserify/blob/master/examples/browserify-shim/package.json
- https://github.com/jmreidy/grunt-browserify
- https://github.com/substack/node-browserify

**Comment by IagoSRL** [comment]
More docs:
- https://github.com/jmreidy/grunt-browserify/issues/181
- http://aeflash.com/2014-05/grunt-browserify-2-x-update.html

I had read this in the past, at first attempts. Basically, the APIs at browserify and browserify-shim that allowed being configured from code has gone, and only read it from the package.json file; then, all the set-up cannot be just in the Grunt task anymore, but split in several files; and the *shim* set-up seems to have switched the kyes-values

**Comment by IagoSRL** [comment]
(pressed comment earlier before :-P) Following, from what I understand:

The *shim* set-up has moved the *path* property to the *key*; that way, the key cannot be used to create an alias to the path, if an alias is wanted must be set at the new *browser* key at package.json; and too, the browserify *alias* option has being replaced by that *browser* key.
Note that lot of people had problems with all that changes; and me, still didn't try it again.

Re-reading the blog post, author have written that the set-up was much slower than before; lot of versions in between, that may changed, and too, it exists *watchify* that may be good to use at our *grunt atwork* task.
Additionally, I think we must merge the two bundles *libs* and *styleguidelibs* (this separation makes no sense anymore, since the styleguide has gone), making easier the removal/change of set-up around shim, alias and external/require. (sorry to not point out this before).

Thanks @situatedbit for the additional docs, useful.

**Comment by situatedbit** [comment]
@IagoSRL when you are working on creating more bundles with our current configuration, do you think it is a good idea to _also_ update browserify? Or, does that make bundling too complex?

**Comment by IagoSRL** [comment]
I was trying to accomplish this and in my latest trials I get it working with latest Browserify but with drawbacks; I did it on top of the @situatedbit work at the branch is360-update-browserify, but with a weird thing at the set-up of 'browserify-shim' that I'm trying to fix properly rather than adding a workaround.

#### Progress
- As happened to @situatedbit, first attempts failed, with our set-up of 'libs bundles'
- To simplify things, I created a branch off *master*, combined 'styleguidelibs', 'libs' and 'app' bundles in one big 'app', and removed the 'tests' and 'landingPages' bundles for now (to recover later). Tried to build and run the webapp, all seems OK.
- I replicated previous set-up in the is360 branch with updated Browserify&Co.
  - The result file is 35KB smaller; maybe some optimizations makes the difference?
  - It does NOT run; I get an error in the console with the set-up of the jquery.fileupload-image plugin
  - It seems like dependencies are not being loaded.
  - In the 'shim' section, I checked the dependencies are correct.
- Quick and dirty: added 'require' calls to all the dependencies of 'jquery.fileupload-image' near the top of the 'app.js' file: now **IT WORKS!**
  - Lines added
```js
require('jquery.fileupload');
require('jquery.fileupload-process');
require('load-image');
require('load-image.ios');
require('load-image.meta');
require('blueimp-canvas-to-blob');
```
- From what I understand, this 'require' lines *must be* included in some way by Browserify-shim when adding them as dependencies; is basically, all the task expected by adding the 'depends' setting.
- I tried to remove the 'depends' setting for this shimmed plugin; it has the same results, so is like doing nothing!
- Note: in our previous version of Browserify-shim (at master) the 'depends' was required and worked as expected.
- I tried adding the dummy `"exports": null` setting on each shim that does not exports (as we had before) but no change and other crazy settings changes.
- I checked documentation and is just says that 'depends' work the way did in the past.
- Workaround: Thinking in add a small module just to do the 'require' lines and named as the module to use inside the app (preventing to add that lines globally, or repetitive on each require of the plugin).

----------

After close that thing, still need to figure out to make the bundles for 'libs', but rather than do that manually I will try a plugin that splits bundles automatically with 'common' modules in a separated bundle, since it makes more sense: https://github.com/substack/browserify-handbook#partition-bundle

**Comment by IagoSRL** [comment]
#### Progress update
- I was able to fix the problems with *shimmed* modules: not by fixing *browserify-shim* or with the previously commented workaround (that I tried but a deeper error appeared), but by replacing the versions used of the affected modules with latest ones; they have support for CJS modules and even published on npm so can be used with Browserify 'as is', without 'shim' and all the set-up looks simpler.
  - Basically, the jquery.file-uploader plugin and dependencies (sub-components, load-image, canvas-to-blob)
- **Updated jQuery to latest, 3.2.1**, as part of get it from npm, to accomplish the commented above, because there were dependency resolution problems.
  - Only plugin I found incompatible was *jquery-mobile*; but I was able to replace it (a custom build) with *detect_swipe* module (that I have used with good results in other projects) that shares the same event names and usage so no refactors needed. Another feature included on that jquery-mobile build was not needed anymore (removed the affected code too).
  - If [some other plugin fails](https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed) with this jQuery version, we can:
    - try to latest version of 2.x series
    - or include the [Migrate Plugin version 3](https://github.com/jquery/jquery-migrate/#README)
- Adapted set-up of Browserify, the 'require' section is not needed, all module alias were moved to the browser field at package.json, some pre-loaded module was not in use.
- Removed unneded getPublicModulesFrom custom module.
- Re-enabled the debugging option (is done differently now), and installed *exorcise* module to split the *source map* generated by Browserify into another file.
- Updated branch with latest from master (using rebase) and fixed the several conflicts that appeared
  - Adjusted set-up of 'stringify'.
- Recovered set-up for *landingPages* and *tests* bundle, now simpler than before (since all they inherits from package.json set-up now).
  - Though, like app.js, they include all the modules without a shared/common bundle (previous *libs*, *styleguidelibs*); that's coming.

**Comment by IagoSRL** [comment]
I removed the initial 'is360-update-browserify` branch and pushed a new one `is360-update-browserify-bundles` with all latest progress here. This one is based on the initial by @situatedbit, with newer work and updated with recent *master* changes resolving lot of conflicts; I tried first to update the original branch, but ends in repeated conflicts that don't want to resolve again.

**Comment by IagoSRL** [comment]
#### Progress update (almost done)
- Tried *partition-bundle* to auto generate the "common.js" file (previously 'libs.js'). Lot of problems, discarded.
- Set-up *factor-bundle*, now "common.js" generates correctly.
  - Had to workaround [some problems](https://github.com/substack/factor-bundle/issues/61) to make it work inside a Grunt task: need to know when ends each spawned sub-task and exit properly, need to get notified of errors when building the factorized files and stop the task.
  - Reorganized app and landingPages tasks as unique appCommon task: is the only way to make factor-bundle to recognize the common parts and extract them.
  - Note: The full Browserify task takes longer now, since it processes at once what previously was 'styeguidelibs', 'libs', and 'app || landingPages'.
  - Integrated 'exorcist' module as part of the factor-bundle and Browserify set-up; removed the grunt-exorcise task.
  - Implemented a manual notification for every auto rebuild.
- Enabled 'watch' mode in Browserify ('watchify'): faster, incremental processing for the 'atwork' task.
  - Reorganized 'watch' task for new set-up.
  - The 'watch:setupChange' subtask auto reloads the running task to apply new project and Grunt settings.
  - Removed `atwork-landingPages`, replaced by a new parameter 'target' when executing atwork/watch: it runs a different set-up for a `target=landing_pages` (this makes possible to customize execution, avoids building landingPages stuff when non working on that). At the terminal `grunt atwork --target=landing_pages`.
  - **Note: `atwork` task now takes longer to start-up** because of 'watchify', because it does an initial build of Browserify in order to being able to do incremental builds on file changes --when working.
- Updated Grunt to latest version (1.0.1)
  - Updated all Grunt plugins in use to latest versions
  - Stylus got updated with it's Grunt plugin, fixed a compatibility issue with latest version.
  - Several modules get updated as dependencies of the Grunt tasks, checked release notes for all looking for compatibility problems and upgrades.
  - Had to fork the plugin 'grunt-bliss' to upgrade it for Grunt 1.x; using this fork directly (it's on my Github account).
- Set-up Grunt-parallel to optimize execution of 'build' and 'build-webapp' tasks, trying to decrease the side effect of new Browserify--factor-bundle set-up.
- Adjusted notifications for tasks to prevent excessive messages:
  - Removed automatic notification for 'build-*' tasks, prevents too much noise on automatic full re-builds.
  - The 'atwork/watch' tasks just trigger a notification as before for every individual task triggered by a file change.
  - But when an automatic full rebuild happens (setupChange), just one notification appear when everything ends.
  - If a notification is wanted when running manually a 'build' task from terminal, add the notify task just after it like `grunt build notify:build` *(there are different notify messages per common tasks, like notify:js, notify:css, notify:html (see app/grunt/aliases.js))*.

PS: Just for the record, I left here a useful official link about Browserify https://github.com/substack/browserify-handbook

**Comment by IagoSRL** [comment]
## DONE

Latest:
- Last review of set-up
- Removed *cssmin* task from running at 'watch' (unneeded for dev).
- Update from *master*
- Testing running the tasks and the app

I'm merging this to *master* now and closing.
**It's required to**
- update any branch with latest content from *master*, let me know any conflict difficult to resolve.
- After pull *master*, and any branch where is merged, run next in the terminal (**careful**: grunt clean will remove all content from 'build' directory --only generated or copied content must exists there, but just in case)
```
npm install
npm prune
grunt clean
grunt
```

Last 'grunt' is just to test the set-up making a new build and test.
