### ISSUE TITLE
Bug S2 Landing page scrolls to top of page when focus on password field

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#377]
ScrollToElement fails on the landing pages. 

This line sets ``scrollingTop`` to ``0``: 
```javascript
var scrollingTop = elementTop + parent.scrollTop() - parent.offset().top;
```
The ``atRoot`` flag should actually apply here, but it's obviously not at the root. The condition needs to be modified to work in the current landing page.

**Comment by IagoSRL** [comment]
Seems the problem was another, just applying the special 'atRoot' logic to calculate the scroll amount was wrong in our current layout. I pushed a fix as part of the branch is367, simplifying logic.

But is strange to me, because my previous experience with this, so I opened issue #378, so we can close this (if is actually fixed) but keep an eye on that.

**Comment by joshdanielson** [comment]
Tested in #367 branch and working.

**Comment by IagoSRL** [comment]
Thanks for the additional testing.

I will close this now and move on; but still please @situatedbit when you can double check this (I know you are not today, no worry), in case there is still a problem we can quickly do your workaround commented at #367 disabling the scrolling at password and continue investigating at #378

**Comment by situatedbit** [comment]
Tested on dev both Chrome and Firefox -- looks good.

**Comment by IagoSRL** [comment]
Thanks @situatedbit for the additional testing.
