### ISSUE TITLE
Revise /onboardingSuccess to include Next Steps

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#385]
- Stay in touch
  - Social media tags
- Get to know your community
  - Join networks.loconomics.com
- Become an owner
  - upgrade to owner plan
  - invites to events
- Download our app

**Comment by IagoSRL** [comment]
@joshdanielson Since you are assigned, I must suppose you are working on this?

The 'upgrade to owner plan' note maybe needs to be done after we complete #191?

**Comment by joshdanielson** [comment]
@IagoSRL yes, I'll take this one and does require #191. Just need to start thinking how to keep users engaged and this will be the best touchpoint to do that. It may even be too much to ask them to upgrade then, I don't know, but will figure that out.

**Comment by joshdanielson** [comment]
Ahhh...good point, my mistake!

**Comment by joshdanielson** [comment]
@situatedbit @IagoSRL take a look at this in the branch and let me know your thoughts before I do a pull request. I think this is a decent base for this release that we can polish.

**Comment by situatedbit** [comment]
@joshdanielson I must have misunderstood when we talked about this last because I was assuming this would entail a couple of different next steps post onboarding success. While I think using a grid when comparing for plans is good, I don't think it will be most effective immediately after onboarding.

The new pro hasn't yet had a chance to even try using the system, and unless they were planning to pay for the upgrade ahead of time, they'd be basing their decision on the onboarding experience. I think an option to upgrade is fine, but it should be one of a couple other buttons, and not the primary activity.

I'm happy to talk about this when I'm in this morning.

**Comment by joshdanielson** [comment]
@situatedbit I agree. This page should probably live on its own and we can mention it in next steps vs it being the main attraction. Let me know whip something up that we can discuss
