### ISSUE TITLE
Remove Booking Policies from onboarding

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#402]
Persona:
[Morgan, established massage therapist](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Morgan.md)

Story:
Because I'm still trying to figure out whether Loconomics is right for me, as a newly-signed-up professional with an established practice and client base, I want to start seeing what my profile looks like quickly and sort out the details later. Booking and cancellation policies are details I can determine later, after I've created my first listing. 

Default to _Acceptance required_ and _Flexible_ cancellation policy.

Other reasons to remove booking policies from onboarding:
- for new free listing plan, we'd like to disable or downplay instant booking

**Comment by situatedbit** [comment]
Decided to postpone this item until we can display success/listing completion message explaining _what happens next_. Would explain and also link to cancellation policy form if the professional wants to change it.

**Comment by IagoSRL** [comment]
@joshdanielson No clarifications here about how to explain/display to professionals which is their default policy, and let him know they can change it (if under an Owner plan) or upgrade plan to have this or that extra option (I think is important that professionals can know what options are available even if the plan they have don't allow it, promoting them).

Related: we have not implemented the restrictions based on plan, so currently every user has all options available thought; I'm thinking if the issues #442 and #328 must be moved to a new Epic and that under the super epic #584, since is important users we start promoting after complete this epics actually see the restrictions and available options (for the set of already implemented features).

**Comment by joshdanielson** [comment]
@IagoSRL check out epic #615 and let me know if that clears it up.

**Comment by IagoSRL** [comment]
Yes, it does, thanks!

**Comment by joshdanielson** [comment]
Closing this epic as all issues completed.
