### ISSUE TITLE
Investigate New Activity Lifecycle

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#457]
Based on proposal A from #423. 

4-hour investigation issue to explore:
1. creating a template for each activity's html
2. releasing activity resources when navigation moves away from the activity
3. I will evaluate implications in code complexity
4. I will try to ascertain whether there are significant performance implications after this change.

**Comment by situatedbit** [comment]
I'm going to create a 4-hour investigation issue to explore:
1. creating a template for each activity's html
2. releasing activity resources when navigation moves away from the activity
3. I will evaluate implications in code complexity
4. I will try to ascertain whether there are significant performance implications after this change.

**Comment by situatedbit** [comment]
Tracking down all of the locations where code assumes activity template is already in the DOM. 

Only a few places assume that an activity has been initialized.

**Comment by situatedbit** [comment]
~1 hour

**Comment by IagoSRL** [comment]
Progress update:
Aligned with changes at #460 weeks ago, I implemented the new activity lifecycle, but in a restricted way so makes it possible to enable it incrementally without waiting for all activities to be refactored (impl details looks a bit as a hack, though).

Basically, the lifecycle where activities instances are removed after used (on shell 'closed' event) and re-created next time, only applies to folder based, individually bundle, activities (the new recommended pattern).

It was required to me to push this changes now because component-based activities require this in order to behave properly and in a predictable way (every time user enters an activity, all component constructors are expected to run --there is no such a 'show' method there, no 'reset' behavior too; that didn't happen with *legacy* lifecycle). This was needed when working on **issue #764** to fix some bugs.
(note: on previous component-based activity, 'paymentAccount', a hack was used to enforce component recreation, since is and old lifecycle activity still, and was preferred to not keep the need for that hack on new work.

-------------

Once #460 is done by refactoring all activities to new pattern, removing unneeded artifacts for the old lifecycle, this implementation can be updated to remove support for old lifecycle and the code being smaller and easier to understand.

**Comment by IagoSRL** [comment]
Moved from *"In Progress"* to **Refactor** pipeline since pending work, aside bugfixes, is a clean-up and refactor of the implementation.

**Comment by IagoSRL** [comment]
Opened #788 as a follow-up of this issue
