### ISSUE TITLE
VPAT Assessment - Preliminary Research

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#465]
As a potential recipient of US government funds, Loconomics needs to adhere to VPAT standards prior to working with any organizations that require it. 

[ITI-VPAT.pdf](https://github.com/loconomics/loconomics/files/1048345/ITI-VPAT.pdf)

**Comment by situatedbit** [comment]
Android and iOS layer their supportive technologies on top of the webview (and equivalent component in iOS). However, I think we only need to be concerned with the web version of the app because it is an alternative form of the same content. Therefore, I think we can limit our concern to the VPAT _Section 1194.22 Web-based Internet information and applications_ criteria.

I'm going to add notes to each of the VPAT criteria:

VPAT Criteria | Matt's Notes
--- | ---
(a) A text equivalent for every non-text element shall be provided (e.g., via "alt", "longdesc", or in element content). |
(b) Equivalent alternatives for any multimedia presentation shall be synchronized with the presentation. |
(c) Web pages shall be designed so that all information conveyed with color is also available without color, for example from context or markup. |
(d) Documents shall be organized so they are readable without requiring an associated style sheet. |
(e) Redundant text links shall be provided for each active region of a server-side image map. |
(f) Client-side image maps shall be provided instead of server-side image maps except where the regions cannot be defined with an available geometric shape. |
(g) Row and column headers shall be identified for data tables. |
(h) Markup shall be used to associate data cells and header cells for data tables that have two or more logical levels of row or column headers. |
(i) Frames shall be titled with text that facilitates frame identification and navigation |
(j) Pages shall be designed to avoid causing the screen to flicker with a frequency greater than 2 Hz and lower than 55 Hz. |
(k) A text-only page, with equivalent information or functionality, shall be provided to make a web site comply with the provisions of this part, when compliance cannot be accomplished in any other way. The content of the text-only page shall be updated whenever the primary page changes. |
(l) When pages utilize scripting languages to display content, or to create interface elements, the information provided by the script shall be identified with functional text that can be read by Assistive Technology. |
(m) When a web page requires that an applet, plug-in or other application be present on the client system to interpret page content, the page must provide a link to a plug-in or applet that complies with §1194.21(a) through (l).  |
(n) When electronic forms are designed to be completed on-line, the form shall allow people using Assistive Technology to access the information, field elements, and functionality required for completion and submission of the form, including all directions and cues.  |
(o) A method shall be provided that permits users to skip repetitive navigation links.  |
(p) When a timed response is required, the user shall be alerted and given sufficient time to indicate more time is required. |

### Resources

- [Section 508 best practices](https://www.section508.gov/best-practices) (see section on technical guidance) 
- [WCAG 2 at a glance](https://www.w3.org/WAI/WCAG20/glance/)
- [WCAG 2](https://www.w3.org/TR/WCAG/)
- [How to Meet WGAC 2](https://www.w3.org/WAI/WCAG20/quickref/)

**Comment by situatedbit** [comment]
Generally speaking, we could improve our semantic markup. We're a little loose about using things like headers, lists, document regions. 

We should also look closely at how text readers handle our hiding/showing templates, components, and elements. We use knockout's ``data-bind: visible`` all over the place. How do text readers respond?

**Comment by joshdanielson** [comment]
@situatedbit just found a better description of what VPAT is and it clarifying that's it's a voluntary statement made by us (using the template) for the governmental agency to gauge the level of accessibility suggesting it varies by agency.

"Voluntary Product Accessibility Template (VPAT) Statement - For U.S. based websites and applications, the level of accessibility is documented using the VPAT or GPAT templates which are used by procurement departments and government agencies for gauging the level of accessibility. For additional information about VPATs, visit [Information Technology Industry Council](http://www.itic.org/)."
