### ISSUE TITLE
Bug S1: Booking Request Confirmation URL Not Working

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#5]
@IagoSRL I just clicked on Irene's email link (I believe it was https://loconomics.com/viewBooking/416) and it led to a blank screen (gray background) with the Loconomics header (she was on an android...totally forgot to get the model, but it was new and it was the browser, assuming chrome).

I then checked and she was already logged in so I clicked on Calendar thinking I could confirm it that way, and got the following error:
![image1](https://cloud.githubusercontent.com/assets/1202838/19954446/a6e16c38-a135-11e6-907c-ab578ac34831.PNG)

**Comment by IagoSRL** [comment]
@joshdanielson After investigate and fix some things, the only way to reach a blank screen like this for me was to be logged as a user that has no rights to see the booking ID (not being either client or professional). 

- If there is no user logged, it redirects to login, and redirects back to booking once is logged showing fine if has the rights.
- If the user is client or professional, it performs a redirect from *viewBooking* to the *appointment/clientApointment* activity for the booking.
  - **Change**: I used *replaceState* here (now that was fixed by @situatedbit) to allow user to go back (before, pressing back returned to *viewBooking* that auto redirects forward again, just bouncing)
  - Allow go back is useful when the link is used internally, like in Inbox/Conversation.
  - **Change**: I updated *conversation* activity to use *viewBooking* links; before was working only for professionals, clients was getting an authorization error.

The blank screen appeared for 'not found' error, that is what server returns both if bookingID don't exists or requester user has no rights. **Change:** now for this and any other error in the operation:
- it shows the error message inside an error modal
- once user closes the error modal gets redirected to dashboard (preventing user gets stopped at a blank screen).

Additionally, for the screenshot on this issue, I **fixed** how some kind of error messages were managed and now that screen will show the error message or contents rather than non useful *'add:'*. This was done at calendar and in others affected activities too.

**Comment by joshdanielson** [comment]
@IagoSRL nice work! All the fixes/changes make sense to me.

**Comment by IagoSRL** [comment]
@joshdanielson I uploaded to *dev* the progress on this (and recent changes merged at master), so you can try to replicate. Except some new error appear because of this changes, I will include in the release, I will do tomorrow.

Other issues in the milestones will get moved to another bugfix release.

**Comment by joshdanielson** [comment]
@IagoSRL I remember this only happening with Irene's android phone so not sure how to try and replicate.

**Comment by IagoSRL** [comment]
:-/   Doubt: May she has logged in with a different user than the one for the booking.? Sounds strange, maybe you ended creating with her more than one user account for some testing or any?

If not that case, what happened may not be what was fixed (still this fixes done are needed):
- Maybe there was **another server error**, and we failed to display the error message (this is fixed now).
- There are a lot of things loading when opening the link, so maybe the problem was taking a lot to load the data, just seeing the blank screen in the meanwhile (in big part because of large webapp, that we need to fix aside) and the load of the booking data to check if exists previous to redirect to the appointment; for this a loading spinner will help.

**Comment by IagoSRL** [comment]
And for testing, if you can test the things I commented were changed or fixed would help, as additional test aside from me.

**Comment by IagoSRL** [comment]
Added loading spinner to viewBooking, uploaded to *dev*

**Comment by joshdanielson** [comment]
@IagoSRL it would have been her only account for live. 

Tested the following with booking 872:
*As service professional*:
- [x] view booking from email confirmation
- [x] view booking from inbox
- [x] view booking from dashboard's upcoming  bookings
- [x] view booking without being logged in, redirecting after login

*As client*:
- [x] view booking from email confirmation
- [x] view booking from inbox
- [x] view booking from dashboard's upcoming  bookings
- [x] view booking without being logged in, redirecting after login

**Comment by IagoSRL** [comment]
I think we can close this since we are unable to reproduce and if it happens again an error message will be displayed (rather than blank screen) that can give us extra information (hoping user share it with us); and since the error was not only at viewBooking but too at calendar looks like a more generic, back-end error, was happening for events/bookings, that we may have fixed. I tried to view the booking as both users involved and worked fine.

**Comment by joshdanielson** [comment]
Agreed, closing.
