### ISSUE TITLE
Bug S1: Invalid user error and Unable to sign up via iOS app via facebook

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#582]
Steps to reproduce:
1. download app from Apple store
2. Alert pops-up and says "invalid user"
3. Dismiss alert
4. sign up as service professional
3. Sign up with Facebook
4. Error says 'specify phone number'
5. It's already been specified 

From user:
i downloaded the app and the alert displays 'invalid user'
then I went to sign up via facebook
and it said 
it's been specified

**Comment by IagoSRL** [comment]
I reviewed the case. We have an 'Incorrect user' error message at server (that I suppose is rather than 'invalid user', quite similar). It happening when trying to log-in Facebook and fails.

The specific user for this case has an account since 2015, but not Facebook linked account; I think what is happening is: trying to log-in with Facebook when has previously signed-up with email instead.
We may review if error messages must get updated to be more specific ("user exists logged email not Facebook", better language) or if that's not good for security/privacy?

The "phone number" required error is happening because is recognizes the sign-up attempt as a 'client', for what we still require the phone. I need to review this still because he looks is trying to sign-up as professional.

**Comment by joshdanielson** [comment]
@IagoSRL the user asked that I remove his account with email and he's going to sign up with facebook (as a service professional). I'll create a new issue if that's unsuccessful. Closing.

**Comment by IagoSRL** [comment]
OK, thanks!
