### ISSUE TITLE
Bug S1: /addressEditor form not able to be saved

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#652]
## Steps to recreate
- Create a new service location or area
- Enter info
- Click "Save changes"
- Form is stuck...no indication it's saved and only option is to cancel

@IagoSRL I spent an hour trying to retrace the code changes and couldn't find anything that I think would affect it, and I'm pretty certain I tested this when making changes so not sure. After it's saved, it should go back to /serviceAddresses

**Comment by IagoSRL** [comment]
Hi Josh, I found this yesterday and make a workaround at the 'autocomplets' branch I'm working on, so is fixed there.
It's something strange, and even if the fix works I call it a workaround because how was before *should* work too (it did it).

**Details:** the 'save' function was attached to the 'form submit' event; now is attached to the 'button click' too. At most forms we have this latest set-up (button click), but is a better experience (usability and accessibility) to have attached to the 'form submit' and make the main button 'type="submit"' (like this one is already). Even I have a note (I need to convert it into an issue) to upgrade all forms to this. But now, suddenly, that setup at addressEditor is broken and don't know why.

**Comment by IagoSRL** [comment]
I updated *dev* and branch is528 with this fix.

Note that the problem with going back after save is not fixed, this is a general bug affecting all forms (it seems), is the bug with `app.successSave` I commented you @joshdanielson a few days; same change with navbars I need to research.

But the most important problem is fixed with a workaround as I explained in previous comment (handler on the button)

**Comment by joshdanielson** [comment]
Thank you!

**Comment by IagoSRL** [comment]
Fixed the global error with `app.successSave`, merged into *master*. So addressEditor both saves and redirects after save as expected.

I will open an issue to try to implement the use of form-submit event rather than button-click for the main form action (since is a good practice), that seems trivial but for some reason is not with problems like the one we saw here at addressEditor. Closing
