### ISSUE TITLE
Accessibility: Clicking "View and Book" links on dev.loconomics.com doesn't speak page title when loaded

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#653]
Other pages seem to work, but these don't. Clicking on them seems to position my cursor on the first link but doesn't speak the header content.

One commonality I've noticed is that, for pages where this works, the page title heading is the first element with visible text in the main section. In these pages, the heading is after a list of other links, which I assume are tab links for switching professions.

**Comment by IagoSRL** [comment]
@joshdanielson Since you did lot of title changes lately, can you double check this?

**Comment by joshdanielson** [comment]
@IagoSRL and @ndarilek these were updated earlier this week. @ndarilek please test again.

**Comment by ndarilek** [comment]
Still not working for me on dev.loconomics.com.

Also, when I click what I assume are tab titles on the top of the 
results page, I don't get feedback when screens change. I.e. if I click 
a View and Book link, then click a different category, I get no feedback 
that the category changed even though it has.)

**Comment by IagoSRL** [comment]
Yes, the links looks like tabs (as in /about) but the content is different because we have not different tab content, is just the same container for each "tab" that changes dynamically after clicking a link; that includes the title. The problem: it happens after the 'auto focus title' code, so there is empty title when happened, and is not notified when clicking another link. Would try to make them work with the tabs code from /about and check if I can fix the problem of focusing title by doing it after loading the content; not sure if need to notify that the page is 'busy' or 'loading' when entering.

**Comment by IagoSRL** [comment]
@ndarilek I did changes and pushed to is528 branch (is NOT at dev.loconomics.com), so you can try if is accessible now. It was more complex because is more dynamic than other tab based activities; moving to another tab triggers a loading for the tab content, I set an 'aria-busy' attribute when is loading at the tab content (at the same element is related with the tab using 'aria-controls'), so hopes that helps if the loading takes more than a second (on my trials was too fast and don't triggered the screen reader). Let me know how it works for you.

**Comment by ndarilek** [comment]
Isn't working any differently for me under Orca. Links change tab 
content, but they don't seem to reset focus to the title heading.

**Comment by IagoSRL** [comment]
Mmm... The title heading is not being focused in the other tabbed interfaces (/about) and seems to work. The main difference here right now is that an asynchrounous task happens when selecting the tab, maybe that affects how Orca or any other SR detects the tab content?

@ndarilek Should I make the component to focus the tab content after change, on any case? The Dequeu examples for accessible tabs don't change the focus :-/

**Comment by ndarilek** [comment]
Yeah, I think focusing on the <h1/> after tab change is the way to go. 
This is how I've made similar things work recently. It's also ideally 
how I'd interact with the content. If I select a tab then I want to 
start reading what was just presented, and the most ideal place to begin 
is from the <h1/>.

**Comment by IagoSRL** [comment]
@ndarilek I'm trying focusing the first h1, and I see a possible problem: when the focus change to the header, you cannot use anymore the arrow keys to move between available tabs (because the tablist lost the focus); too, with NVDA, focusing the header just reads 'header' after the H1 gets the focus, but don't starts reading the content. I added a 1 second delay on focusing the header, but let me know how do you use to do this. I pushed the change at is528, but I can revert it if wrong.

**Comment by ndarilek** [comment]
I'm really confused. Again, on commit 63cdc7f, I don't see any change. 
Further, I don't see that I can arrow left/right through the list of 
tabs. They all appear to be links. Am I on the right commit? It's 
possible Orca doesn't support ARIA tabs, but I doubt that as I'm pretty 
sure I've used them before.

Thanks.

**Comment by joshdanielson** [comment]
@ndarilek same thing as my last comment, I think you'll have to always sync the branch will all of the latest commits before testing. @IagoSRL can you confirm this as the best method?

**Comment by ndarilek** [comment]
To be clear, I'm always doing a `git pull`, then checking out 
origin/is528... So I'm definitely running the latest code, but I wasn't 
clear on which tasks needed to be run to sync build/, and maybe it 
should be completely regenerated when making major changes like 
switching branches? I'll wipe out build/ whenever I switch branches from 
now on.

In any case, these screens now behave more or less as described. Now 
that I understand how they're intended to work, and that tab navigation 
is arrow-based, I'd advise removing the h1-focus code. Apologies, I made 
that recommendation before experiencing the page as a series of tabs. 
With arrow navigation, it is clear when a new page is reached without 
having to move focus away from the tabs.

**Comment by joshdanielson** [comment]
@IagoSRL please see @ndarilek 's comment about h1 focus.

**Comment by IagoSRL** [comment]
Focus removed. Closing this issue as I understand is done, but re-open in case is not
