### ISSUE TITLE
Evaluate switching to Yarn

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#755]
Might be nice to consider switching package managers from NPM to [Yarn](https://yarnpkg.com). Advantages:

 * Much faster. Downloads in parallel, caches packages locally. Subsequent `yarn install` runs with a warm cache finish in seconds, or less.
 * More intelligent package resolution. I'm not sure #750 would have manifested under Yarn.
 * Nicer developer experience. Any binaries in node_modules/.bin can be run directly (I.e. with grunt-cli as a dependency, `yarn grunt atwork` runs Grunt directly without the user needing their own installation.)

I ran into some minor issues attempting this myself, but I'll sink half an hour or so putting together a PR for evaluation.

**Comment by IagoSRL** [comment]
With PR #757 and after some conversation, we did the switch to Yarn, so closing this.

@ndarilek Feel free to propose changes to Travis set-up to use Yarn rather than NPM and prevent global installation of Grunt, if any of that makes sense and makes the process faster and more stable (I think you have it that way initially and some confusion in the middle rollback that; you have more experience than me with both Yarn and Travis, so I trust your judgment here).
