### ISSUE TITLE
Hault the ability for users to create new job title IDs

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#803]
## User Story
As Loconomics, we want to make it easy for users to add their own job titles while still maintaining minimal mappings for suggesting solutions. To accomplish this, we will maintain a list of aliases for job titles and when a user creates a title not on the list, it is flagged to staff to research if it can be mapped to an existing job title. 
See [Google Drive](https://docs.google.com/spreadsheets/d/162RuLkbMf3iwWuzeWTk4iz6McpWmzFn64Y33i4D7_4g/edit?usp=sharing))

**Comment by IagoSRL** [comment]
@joshdanielson Remember to add the generic pricing types for the new job ID "-2"

**Comment by joshdanielson** [comment]
@IagoSRL done. I also added it to the positions table as it wasn't there yet.

**Comment by IagoSRL** [comment]
@joshdanielson I found a roadblock problem with the -2 approach to custom job titles. Since the user listings at Loconomics are identified by the jobTitleID, they can only add one job title with custom name, because cannot be two with the same ID. Don't know how I didn't think on this earlier.

So, same as happens with the external listings and usage of platformID (were we introduced a different, autoincremental ID to allow for more than one 'other' platform), we need a new ID for listings (formerly, [userprofilepositions]).
To add the new column is not a problem just for that table, we can add it, auto populate values and make it single primary key; but then we need to add it too to all related tables and push the new values removing the jobTitleID; and update all APIs and management of data both in server and App that are based on jobTitleID.

We can continue without doing that change by only allowing one custom job title by user, as the more realistic change right now without breaking everything else and still doing this change to hault new job titles

**Comment by joshdanielson** [comment]
@IagoSRL that all makes sense and makes sense to just allow one for now with a new issue for adding listingIDs (seems more organized in the long run) to prioritize after.

**Comment by IagoSRL** [comment]
Didn't see your previous comment: in the branch I have a script to add the position -2 to the table but not applied to *dev* since I didn't uploaded this branch changes there still. Hope your data changes for pricing types have a script

**Comment by IagoSRL** [comment]
I was getting a bit crazy when realizing the need for a new ID. But more calm now, I'm thinking how can we approach to add it incrementally, by adding it soon and start using it along the jobTitleID up to when we have it complete. Actually, we should start adding some new names in the API (a path to v2 REST API) as using /me/listings/{listingID} as replacement for me/userJobProfile/{jobTitleID} while keeping both until all is updated (and Apps in the app store).

**Comment by joshdanielson** [comment]
Here's the commit with the pricing types: https://github.com/loconomics/loconomics/commit/46f01f8f5d3ff102b2b3f6249073f2ff8b4a8c68

**Comment by joshdanielson** [comment]
@iagosrl was just thinking to keep in mind that UserListingSolution and UserListingSpecialization could use the new UserListingID since that will be a manual process to migrate the data over anyway. Just a thought so disregard if distraction.

**Comment by IagoSRL** [comment]
I did a general progress on the Epic, preparing for #832 (to don't need to touch old code), basically on moving obsolete stuff from data module userJobProfile to userListings (listing deactivation, reactivation, deletion, updates, creation) and I removed that old module already, and any reference for synchronization between both, plus some bugfixes of things found by the way (as of: deleting a listing could throw error sometimes, because tried a 'go back' rather a 'go to /listings').

It's all pushed to the branch, but nothing updated on *dev*. There are lot of changes near everywhere so will need lot of testing.

**Comment by IagoSRL** [comment]
> was just thinking to keep in mind that UserListingSolution and UserListingSpecialization could use the new UserListingID 

I agree, I will review to add the field even if not using it still as the way to identify the user listings, except that new tables/APIs

**Comment by IagoSRL** [comment]
Not sure if commented in the other issues, but I did the userListingID change at UserListingSpecialization and UserListingSolution tables this morning and applied to *dev*.
