### ISSUE TITLE
Add login data to track last login and session length

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#828]
### User Story
As Loconomics Staff, we would like to see information about a user's login behaviors so we can better understand their engagement with the app.

#### To-do (could be in conjunction with #827)
- [x] Decide on information to store (@IagoSRL @ndarilek please review/edit). This may be a [useful reference document](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet)
  - UserID
  - AuthorizationID
  - CreatedDate
  - DeletedDate
  - UserAgent (Operating System)
We should be able to extrapolate last login, number of logins, and session length
- [x] Set up the population of the data

**Comment by IagoSRL** [comment]
I was thinking we can use the new [authorizations] table for this, just adding DeletedDate/SessionEndDate column for removal (rather than actual removal), being current CreatedDate the SessionStartDate.
It includes a userAgent and clientAddress (IP) fields too.

Note @ndarilek, If we end adding that sof-delete column, we just do a small change in the SQL query for check the valid token
```sql
SELECT UserID FROM authorizations WHERE DeletedDate is null AND token like @token
```

**Comment by IagoSRL** [comment]
@joshdanielson my latest changes at #827 should satisfy the needs here, at the authorizations table. So I put this at QA too, do some trials with the *dev* site so we try both issues, if can do login--logout several times with same user and check database stores the expected thing.

**Comment by joshdanielson** [comment]
@IagoSRL tested and working for last login and logout. Hard to tell the session length if they don't log out, but I suppose that's hard to tell in any case. Closing the browser tab did not add a "DeletedDate".

**Comment by IagoSRL** [comment]
Yes, this only tracks how much that authentication is active (logged and logged out from a device or browser). That can be never even if they logged and didn't take care to press log out, just stop using the site or the App (even uninstalling it -there is a way to know this, using native push-notifications, extra work on app plugins and server, or Google analytics along with data from stores), or still using it.

But we have already the 'LastActivityTime' data at UserStats table, that is updated on every request to the server (loading page or accessing REST API). Even a LastLoginTime. It is supposedly working.

I think Google Analytics should be a better place to analyze sessions, since we are sending data on each 'page view' (activity view), and other points if we want.

**Comment by joshdanielson** [comment]
@IagoSRL all good and agree that Google Analytics is better for sessions but good to know we can get it from UserStats.  Close this issue if you like.
