### ISSUE TITLE
Fix credentials text on /listingEditor

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#841]
### To-do
@IagoSRL small favor and out of scope of priorities but I see it all the time and should be an easy, html/css only change. Can you try and fix the html here that's getting pushed to the right in /listingEditor? 
![screen shot 2018-03-13 at 11 06 21 am](https://user-images.githubusercontent.com/1202838/37360941-e37f220c-26ae-11e8-87a2-3ef97d2b9016.png)

**Comment by IagoSRL** [comment]
Done, check the issue branch.

It happened only when no licenses added. The 'em' message that displays when empty was placed at the header rather than after (as in other cases).

Additionally, I removed the duplicated add/edit button at the block header ('Credentials and verifications'): it does the same as the one for the 'Professional credentials' sub-section and can be confusing (was for me).

**Comment by joshdanielson** [comment]
@IagoSRL tested and looks good. Closing
