### ISSUE TITLE
Bug S1 (Live Site): Error when loading Landing Pages

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#845]
### Long Description
When visiting a landing page, there is an error message "There was an error loading
BadAuthorization: Authorization expired, needs to login again". This happens on both live and dev and in incognito windows.
![screen shot 2018-03-19 at 3 23 57 pm](https://user-images.githubusercontent.com/1202838/37627863-c4498bb8-2b93-11e8-80fa-d7ff2e836c28.png)

**Comment by IagoSRL** [comment]
If I enter with a logged user at loconomics.com, no problem.
I logged out and went again to the landing page URL: `NotFound: There are no saved authorization`
This matches some of the other screenshots they send us.
The screenshot opening this issue says as error: `BadAuthorization: Authorization expired, needs to login again`.
I found both errors in code and the fix; latest changes in authorization process has introduced some change in the app to manage them, adding new exceptions that are throw and managed by initialization code, that happens to be at `app.js` (entry point), while other code goes in shared modules, anything on that file is not and the special setup of landing pages make them have it's own entry point, `landingPage.js`, that by mistake I didn't update it with that new management code.

Source of both error messages is very similar (both at `/app/js/data/userAuthorization.js`), one applies to user previously logged (the BadAuthorization ones) and the other to anonymous users.

Actually, the code that triggers that is a 'session restore' that at landing is not needed since we should work only with anonymous users there, so I just removed the attempt to restore and everything goes fine.

**Comment by IagoSRL** [comment]
I had some problems releasing the bugfix just from the last *live* state, so I merged into master, where we had already a few stable changes and published as version 1.9.1. For me is working but please @joshdanielson try it and close it if didn't fail again. Try both with a logged user and anonymous.

**Comment by joshdanielson** [comment]
Tested with both anonymous and logged in, working, closing.
