### ISSUE TITLE
Bug S2: "steps to activate your listing:" alerts not showing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#849]
### Bug Description
After completing onboard and ending up on /listingEditor, the steps to activate no longer are showing ("required" labels are still working). I'm not sure which release when this started happening.

#### Screenshot
![screen shot 2018-03-23 at 5 23 10 pm](https://user-images.githubusercontent.com/1202838/37858920-2c26ffe4-2ec9-11e8-8e14-e06c47b3597a.png)

**Comment by IagoSRL** [comment]
I was fixing several bugs when researching this, some hidden at the console, and finally found something:
- the listingEditor.js is doing requests to the public API of users to get the job profile data
- that one doesn't return info about the alerts of the user listing, so cannot be populated in the UI
- the section ("You're almost there!") is displayed based on the status, that is available as 'not complete', rather than use the count of pending alerts, leading to this mid-state.
- Strange: it seems we updated at some point the server 'public' users API to return data publicly hidden if the requester and the user requested is the same (so works for listingEditor). But that change does not include some non public info as the list of alerts. This could get updated, but can lead to more complex code and confusing API scope. Should use the correct API.

**Comment by IagoSRL** [comment]
Found the problem, it's actually about the subset of data stored with the new cache mechanism I'm introducing at new data modules; still, I found there is a mix of public/private APIs at that activity that make it confusing to debug, but the problem is not because of that.

*Sorry so many spam comments*

**Comment by IagoSRL** [comment]
I fixed this, it's at *dev* and will upload to *live*.

Finally, **was a server change**. Not sure how the front-end change had triggered this or there is some edge case at the back-end that didn't happened until now, but is located and fixed (and annotated in code). Specifically, was at LcRest/UserJobTitle.cs:BindAlerts method, for some reason the alerts attached to each title were lost when returning the, lazy consumed, list (like new items being generated rather than reused, not sure how at some point this worked differently).
