### ISSUE TITLE
Bug S1: Cannot read property "hasAttributes" of null

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#875]
### Bug Description
Happens when clicking on some listings (I searched for massage therapists in san francisco and click on the first couple):
![screen shot 2018-07-12 at 9 26 03 am](https://user-images.githubusercontent.com/1202838/42648194-0770cb96-85bb-11e8-9fb8-c84d76ae31dc.png)
![screen shot 2018-07-12 at 9 26 27 am](https://user-images.githubusercontent.com/1202838/42648195-078ff944-85bb-11e8-91e3-6e290499b9d1.png)

**Comment by IagoSRL** [comment]
Current listing activity does not choose a job title automatically, has to come in the URL. That URLs has not one and thrown an error (because the objects to contain job-title specific info has nothing).
So:
- The search pages (as activity searchJobTitle) is not including the job title in URLs, and must to.
- Are there situations where we should allow a non-job title URL for listing so we choose one automatically?

**Comment by IagoSRL** [comment]
Done the first point, fixing the search results URL and working, releasing to *live*.

Researched the second point, we had that auto selection actually but for some reason fails to select and prepare the data before this is requested, throwing.

**Comment by joshdanielson** [comment]
@IagoSRL seems to be working now as you say. I do not think there are any instances (yet) that would require a non-job-title URL. I guess we used to have it by the user and all their job titles, but we moved away from it.

**Comment by IagoSRL** [comment]
OK, I just removed code that supported that auto-selecting job title when is not in the URL, since is not working and not used. So we can close this.
I tested and merged into master.
